### ISSUE TITLE
Truffle configs: export config as default

### ISSUE THREAD

**Issue by sohkai** [aragon/contract-helpers#13]
Rather than forcing users to use `require('@aragon/truffle-config-v*/truffle-config'), we should just simply it so that they can use `require('@aragon/truffle-config-v*)`.

I believe this can be done by just updating the `main` key in the package.json, but will need to double check.

**Comment by 0xGabi** [comment]
Will come to this in the next couple of days, sorry that took longer than it should 🤕

**Comment by 0xGabi** [comment]
Yes, you were right, as stated [here](https://flaviocopes.com/package-json/#main)
