### ISSUE TITLE
test-helpers: assertThrow across truffle v4 and truffle v5

### ISSUE THREAD

**Issue by sohkai** [aragon/contract-helpers#19]
Apparently [truffle v5 now has a different error structure (`error.reason` is already provided)](https://github.com/aragonone/voting-connectors/pull/43#discussion_r362749645).

We should make sure to handle both these versions in our `assertThrow` helpers so that it can be used generically across truffle versions.

**Comment by 0xGabi** [comment]
Solved with #20
