### ISSUE TITLE
Fail loudly on attempts to use Web3 1.x

### ISSUE THREAD

**Issue by ajsantander** [aragon/contract-helpers#25]
Atm, you can use these helpers with Web3 1.x, but all sort of silent failures start to appear. For example, this:

    // Web3 1.x inverts the order of the parameters of the sign function:
    // Web3 0.x => web3.eth.sign(address, dataToSign, [, callback])
    // Web3 1.x => web3.eth.sign(dataToSign, address [, callback])

**Comment by sohkai** [comment]
Alternatively we can do a major version upgrade to only support web3@1.x and fail loudly on web3@0.2.x.

**Comment by sohkai** [comment]
We will be doing a major upgrade to only support `web3@1.x` and marking it as a peer dependency.
