### ISSUE TITLE
URGENT: Fix test-helpers, contract-test-helpers, contract-helpers-test mess!

### ISSUE THREAD

**Issue by ajsantander** [aragon/contract-helpers#27]
This continues to be something that brings a terrible DX. Fixing it should be simple and have a high impact on the DX. We should define a simple solution and either delete all the NPM packages created in between or throw a HUGE warning (which explains what's the right thing to use) whenever someone attempts to use them.

My suggested solution is to use this: https://github.com/aragon/contract-helpers, rename it to aragon/helpers and follow this nomenclature for npm packages: @aragon/helpers-x.

**Comment by sohkai** [comment]
Closing; we will align on `@aragon/contract-helpers-test`.
